### ISSUE TITLE
FIXED options arent captured for block matrices when indexing

### ISSUE THREAD

**Issue by barrettk** [metrumresearchgroup/nmrec#28]
I'll admit I haven't done a thorough investigation here in terms of determining the root cause of this, but it does seem like a bug. I am currently trying to tabulate `FIXED` parameters in matrices for the new `bbr` jitter feature, so I know which values (if any) to ignore.

using `bbr`'s example complex model:
```r
MODEL_DIR_C <- system.file("model", "nonmem", "complex",   package = "bbr")
.mod <- read_model(file.path(MODEL_DIR_C, "example2_saemimp"))
```

Though it is a prior record in this case, the `FIX` option could be in a regular block matrix as far as im aware:
```
$OMEGA BLOCK(4)
0.01 FIX
0.0  0.01
0.0 0.0 0.01
0.0 0.0 0.0 0.01
```

As you can see below, the `FIX` is not captured here in the block matrix:
```r
ctl <- nmrec::read_ctl(get_model_path(.mod))
omegas = nmrec:::create_param_index(ctl, "omega")
> omegas$details[[2]]
$type
[1] "block"

$subtype
[1] "plain"

$size
[1] 4

$popts
$popts[[1]]
0.01

$popts[[2]]
0.0

$popts[[3]]
0.01

$popts[[4]]
0.0

$popts[[5]]
0.0

$popts[[6]]
0.01

$popts[[7]]
0.0

$popts[[8]]
0.0

$popts[[9]]
0.0

$popts[[10]]
0.01
```

However, it is captured for SIGMA (not a prior record in this case):
```
$SIGMA
(1.0 FIXED)
```
```r
sigmas = nmrec:::create_param_index(ctl, "sigma")
> sigmas$details
[[1]]
[[1]]$type
[1] "diagonal"

[[1]]$subtype
[1] "implicit"

[[1]]$size
[1] 1

[[1]]$popts
[[1]]$popts[[1]]
(1.0 FIXED)
```

I wondered if parentheses were required, and attempted that as well. This error doesnt surprise me though, as I didnt think you could use parentheses in a block matrix anyways. Pasting below in case it's relevant/not desired:

#### With parentheses:
```
$OMEGA BLOCK(4)
(0.01 FIX)
0.0  0.01
0.0 0.0 0.01
0.0 0.0 0.0 0.01
``` 

```r
> omegas = nmrec:::create_param_index(ctl, "omega")
Error in `param_append_num_opt()`:
! Expected numeric value for init, got "FIX"
```

**Comment by kyleam** [comment]
It sounds like you're assuming that `FIXED` would apply to individual values rather than the entire block.  Do you have a reason to think that's the case?

From the NONMEM `$OMEGA` docs:

```
      The following options apply to the entire block  and  may  appear
      anywhere among the list of initial estimates:

      FIXED  indicates that the entire block is constrained to be fixed
      to its initial estimate.
```

---

In case it helps, here is the script I use on Metworx for two purposes:

 * check whether control stream syntax is valid

 * check is two different forms of the control stream give an identical FCON.


```sh
#!/bin/sh

set -eu

usage="usage: $0 CTL <FCON reference>"

ctl=${1?$usage}
ref=${2?$usage}

/opt/NONMEM/nm75/tr/NMTRAN.exe <"$ctl"

test -e "$ref" || {
    printf >&2 '\n%s does not exist, copying FCON to %s instead\n' \
           "$ref" "$ref"
    cp FCON "$ref"
    exit 1
}

cmp FCON "$ref" && printf '\nFCON matches %s\n' "$ref"
```

To use it, put it in an executable file (say `check.sh`) in some scratch directory, and call it like so: `./check.sh foo.ctl foo.fcon`.

If you just want to make sure the syntax is valid, `foo.fcon` can be anything that isn't an existing file from a previous run.  In cases where you want to see if control stream A and B give the same result, `foo.fcon` should be a non-existing file for the first call with A.  The second call with control stream B should reuse the name.

**Comment by barrettk** [comment]
@kyleam 

>    FIXED  indicates that the entire block is constrained to be fixed to its initial estimate.

If that is the case, would you expect FIXED to have shown up somewhere in `omegas$details`?  Will look at the script you said in closer detail, but just curious if that option is intentionally captured somewhere else instead?

**Comment by barrettk** [comment]
That makes sense. I have a follow up question, but ill continue it offline since the issue I made isn't a bug and can be marked as resolved. Thanks for the added clarity.
